### ISSUE TITLE
Compile error when running `npm run dev-bundle`

### ISSUE THREAD

**Issue by michielbdejong** [inrupt/solid-auth-fetcher#171]
This is the error I see when following the readme instructions up to `npm run dev-bundle`:
```sh
[2] ERROR in ./src/index.js
[2] Module build failed (from ./node_modules/babel-loader/lib/index.js):
[2] Error: Cannot find module '@babel/compat-data/corejs3-shipped-proposals'
[2] Require stack:
[2] - /Users/michiel/gh/inrupt/solid-auth-fetcher/examples/bundle/node_modules/@babel/preset-env/lib/polyfills/corejs3/usage-plugin.js
[2] - /Users/michiel/gh/inrupt/solid-auth-fetcher/examples/bundle/node_modules/@babel/preset-env/lib/index.js
[2] - /Users/michiel/gh/inrupt/solid-auth-fetcher/examples/bundle/node_modules/@babel/core/lib/config/files/plugins.js
[2] - /Users/michiel/gh/inrupt/solid-auth-fetcher/examples/bundle/node_modules/@babel/core/lib/config/files/index.js
[2] - /Users/michiel/gh/inrupt/solid-auth-fetcher/examples/bundle/node_modules/@babel/core/lib/index.js
[2] - /Users/michiel/gh/inrupt/solid-auth-fetcher/examples/bundle/node_modules/babel-loader/lib/index.js
[2] - /Users/michiel/gh/inrupt/solid-auth-fetcher/examples/bundle/node_modules/loader-runner/lib/loadLoader.js
[2] - /Users/michiel/gh/inrupt/solid-auth-fetcher/examples/bundle/node_modules/loader-runner/lib/LoaderRunner.js
[2] - /Users/michiel/gh/inrupt/solid-auth-fetcher/examples/bundle/node_modules/webpack/lib/NormalModule.js
[2] - /Users/michiel/gh/inrupt/solid-auth-fetcher/examples/bundle/node_modules/webpack/lib/NormalModuleFactory.js
[2] - /Users/michiel/gh/inrupt/solid-auth-fetcher/examples/bundle/node_modules/webpack/lib/Compiler.js
[2] - /Users/michiel/gh/inrupt/solid-auth-fetcher/examples/bundle/node_modules/webpack/lib/webpack.js
[2] - /Users/michiel/gh/inrupt/solid-auth-fetcher/examples/bundle/node_modules/webpack-dev-server/bin/webpack-dev-server.js
[2]     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:966:15)
[2]     at Function.Module._load (internal/modules/cjs/loader.js:842:27)
[2]     at Module.require (internal/modules/cjs/loader.js:1026:19)
[2]     at require (internal/modules/cjs/helpers.js:72:18)
[2]     at Object.<anonymous> (/Users/michiel/gh/inrupt/solid-auth-fetcher/examples/bundle/node_modules/@babel/preset-env/lib/polyfills/corejs3/usage-plugin.js:10:55)
[2]     at Module._compile (internal/modules/cjs/loader.js:1138:30)
[2]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
[2]     at Module.load (internal/modules/cjs/loader.js:986:32)
[2]     at Function.Module._load (internal/modules/cjs/loader.js:879:14)
[2]     at Module.require (internal/modules/cjs/loader.js:1026:19)
[2] Child html-webpack-plugin for "index.html":
[2]      1 asset
[2]     Entrypoint undefined = ./index.html
[2]     [./node_modules/html-webpack-plugin/lib/loader.js!./src/index.html] 220 bytes {0} [built]
[2] ℹ ｢wdm｣: Failed to compile.
```

**Comment by michielbdejong** [comment]
This is fixed in https://github.com/solid/solid-auth-fetcher/commit/497b3ba58aaabbc70c6fb507f82db8e0d52cd179
