### ISSUE TITLE
TypeError: JWT must be a string

### ISSUE THREAD

**Issue by michielbdejong** [inrupt/solid-auth-fetcher#187]
* Run `npm run dev-server`
* browse to http://localhost:3001
* fill in http://localhost:9001/ids/jackson#me as the user's webid
* on http://localhost:9001/login log in as jackson / ItsCoolGuy&MrFunkWhyCoolGuyWhy
* you'll see an error appear:
```sh
TypeError: JWT must be a string
    at Object.module.exports [as decode] (/Users/michiel/gh/inrupt/solid-auth-fetcher/examples/test-helper/node_modules/jose/lib/jwt/decode.js:6:11)
    at /Users/michiel/gh/inrupt/solid-auth-fetcher/examples/test-helper/src/test-server.ts:77:27
    at Layer.handle [as handle_request] (/Users/michiel/gh/inrupt/solid-auth-fetcher/examples/test-helper/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/michiel/gh/inrupt/solid-auth-fetcher/examples/test-helper/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/Users/michiel/gh/inrupt/solid-auth-fetcher/examples/test-helper/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/Users/michiel/gh/inrupt/solid-auth-fetcher/examples/test-helper/node_modules/express/lib/router/layer.js:95:5)
    at /Users/michiel/gh/inrupt/solid-auth-fetcher/examples/test-helper/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/Users/michiel/gh/inrupt/solid-auth-fetcher/examples/test-helper/node_modules/express/lib/router/index.js:335:12)
    at next (/Users/michiel/gh/inrupt/solid-auth-fetcher/examples/test-helper/node_modules/express/lib/router/index.js:275:10)
    at Immediate._onImmediate (/Users/michiel/gh/inrupt/solid-auth-fetcher/examples/test-helper/node_modules/express-session/index.js:495:7)

**Comment by michielbdejong** [comment]
@jaxoncreed any idea what may be causing this?

**Comment by michielbdejong** [comment]
I can no longer reproduce this, closing.
