### ISSUE TITLE
`npm run browser-dev` not working unless you run `npm run test` first

### ISSUE THREAD

**Issue by michielbdejong** [inrupt/solid-auth-fetcher#21]
The first time I ran `npm run browser-dev` it didn't work. Then I ran `npm run test`, that did work (asked me to give TestCafe Browser Tools permission to record the screen and then a few more 'allow' dialogs popped up, but I'm guessing that would only be for running TestCafe).

Then I tried `npm run browser-dev` again, and it did work! So could it be that there's a build step that `npm run browser-dev` relies on to have been run first? Here's the log from the time it didn't work (you can probably reproduce this by cloning the repo in a clean directory and doing only `npm i`, `npm run bootstrap` and `npm run browser-dev`:
```sh
~/gh/inrupt/solid-auth-fetcher $ npm run browser-dev

> solid-authenticator-root@ browser-dev /Users/michiel/gh/inrupt/solid-auth-fetcher
> concurrently "lerna run test-server-dev --stream" "lerna run build-core-watch --stream" "lerna run browser-dev --stream"

[1] lerna notice cli v3.14.2
[2] lerna notice cli v3.14.2
[0] lerna notice cli v3.14.2
[2] lernalerna info Executing command in 1 package: "npm run build-core-watch"
[2]  info Executing command in 1 package: "npm run browser-dev"
[0] lerna info Executing command in 1 package: "npm run test-server-dev"
[1] @solid/authenticator-core: > @solid/authenticator-core@0.0.0 build-core-watch /Users/michiel/gh/inrupt/solid-auth-fetcher/packages/authenticator-core
[1] @solid/authenticator-core: > tsc-watch --preserveWatchOutput -p tsconfig.build.json
[2] @solid/authenticator-browser: > @solid/authenticator-browser@0.0.0 browser-dev /Users/michiel/gh/inrupt/solid-auth-fetcher/packages/authenticator-browser
[2] @solid/authenticator-browser: > webpack-dev-server --config webpack.config.js --env.env=dev
[0] @solid/authenticator-test-server: > @solid/authenticator-test-server@0.0.0 test-server-dev /Users/michiel/gh/inrupt/solid-auth-fetcher/packages/authenticator-test-server
[0] @solid/authenticator-test-server: > ts-node-dev src/test-server.ts
[1] @solid/authenticator-core: 11:00:51 AM - Starting compilation in watch mode...
[0] @solid/authenticator-test-server: Using ts-node version 8.6.2, typescript version 3.7.3
[0] @solid/authenticator-test-server: Mon, 16 Mar 2020 10:00:52 GMT body-parser deprecated undefined extended: provide extended option at src/test-server.ts:27:31
[0] @solid/authenticator-test-server: Mon, 16 Mar 2020 10:00:52 GMT express-session deprecated undefined resave option; provide resave option at src/test-server.ts:28:34
[0] @solid/authenticator-test-server: Mon, 16 Mar 2020 10:00:52 GMT express-session deprecated undefined saveUninitialized option; provide saveUninitialized option at src/test-server.ts:28:34
[0] @solid/authenticator-test-server: Test Server listening on port 9001
[2] @solid/authenticator-browser: ℹ ｢wds｣: Project is running at http://localhost:9000/
[2] @solid/authenticator-browser: ℹ ｢wds｣: webpack output is served from /
[2] @solid/authenticator-browser: ℹ ｢wds｣: Content not from webpack is served from /Users/michiel/gh/inrupt/solid-auth-fetcher/packages/authenticator-browser/browserDist
[2] @solid/authenticator-browser: ✖ ｢wdm｣: Hash: e30b2a64753866df3775
[2] @solid/authenticator-browser: Version: webpack 4.42.0
[2] @solid/authenticator-browser: Time: 3286ms
[2] @solid/authenticator-browser: Built at: 03/16/2020 11:00:55 AM
[2] @solid/authenticator-browser:                         Asset      Size  Chunks             Chunk Names
[2] @solid/authenticator-browser:                    index.html  1.07 KiB          [emitted]  
[2] @solid/authenticator-browser: solid-authenticator.bundle.js  7.49 MiB    main  [emitted]  main
[2] @solid/authenticator-browser: Entrypoint main = solid-authenticator.bundle.js
[2] @solid/authenticator-browser: [0] multi (webpack)-dev-server/client?http://localhost:9000 ./src/index.browser.ts 40 bytes {main} [built]
[2] @solid/authenticator-browser: [../../node_modules/ansi-html/index.js] /Users/michiel/gh/inrupt/solid-auth-fetcher/node_modules/ansi-html/index.js 4.16 KiB {main} [built]
[2] @solid/authenticator-browser: [../../node_modules/ansi-regex/index.js] /Users/michiel/gh/inrupt/solid-auth-fetcher/node_modules/ansi-regex/index.js 135 bytes {main} [built]
[2] @solid/authenticator-browser: [../../node_modules/strip-ansi/index.js] /Users/michiel/gh/inrupt/solid-auth-fetcher/node_modules/strip-ansi/index.js 161 bytes {main} [built]
[2] @solid/authenticator-browser: [../../node_modules/url-parse/index.js] /Users/michiel/gh/inrupt/solid-auth-fetcher/node_modules/url-parse/index.js 12.4 KiB {main} [built]
[2] @solid/authenticator-browser: [../../node_modules/webpack-dev-server/client/index.js?http://localhost:9000] (webpack)-dev-server/client?http://localhost:9000 4.29 KiB {main} [built]
[2] @solid/authenticator-browser: [../../node_modules/webpack-dev-server/client/overlay.js] (webpack)-dev-server/client/overlay.js 3.51 KiB {main} [built]
[2] @solid/authenticator-browser: [../../node_modules/webpack-dev-server/client/socket.js] (webpack)-dev-server/client/socket.js 1.53 KiB {main} [built]
[2] @solid/authenticator-browser: [../../node_modules/webpack-dev-server/client/utils/createSocketUrl.js] (webpack)-dev-server/client/utils/createSocketUrl.js 2.91 KiB {main} [built]
[2] @solid/authenticator-browser: [../../node_modules/webpack-dev-server/client/utils/log.js] (webpack)-dev-server/client/utils/log.js 964 bytes {main} [built]
[2] @solid/authenticator-browser: [../../node_modules/webpack-dev-server/client/utils/reloadApp.js] (webpack)-dev-server/client/utils/reloadApp.js 1.59 KiB {main} [built]
[2] @solid/authenticator-browser: [../../node_modules/webpack-dev-server/client/utils/sendMessage.js] (webpack)-dev-server/client/utils/sendMessage.js 402 bytes {main} [built]
[2] @solid/authenticator-browser: [../../node_modules/webpack/hot sync ^\.\/log$] (webpack)/hot sync nonrecursive ^\.\/log$ 170 bytes {main} [built]
[2] @solid/authenticator-browser: [./src/index.browser.ts] 3.78 KiB {main} [built]
[2] @solid/authenticator-browser: [./src/index.ts] 814 bytes {main} [built] [2 errors]
[2] @solid/authenticator-browser:     + 328 hidden modules
[2] @solid/authenticator-browser: ERROR in ./src/index.ts
[2] @solid/authenticator-browser: Module not found: Error: Can't resolve '@solid/authenticator-core' in '/Users/michiel/gh/inrupt/solid-auth-fetcher/packages/authenticator-browser/src'
[2] @solid/authenticator-browser:  @ ./src/index.ts 6:43-79
[2] @solid/authenticator-browser:  @ ./src/index.browser.ts
[2] @solid/authenticator-browser: ERROR in /Users/michiel/gh/inrupt/solid-auth-fetcher/packages/authenticator-browser/src/BrowserJoseUtility.ts
[2] @solid/authenticator-browser: ./src/BrowserJoseUtility.ts
[2] @solid/authenticator-browser: [tsl] ERROR in /Users/michiel/gh/inrupt/solid-auth-fetcher/packages/authenticator-browser/src/BrowserJoseUtility.ts(18,26)
[2] @solid/authenticator-browser:       TS2307: Cannot find module '@solid/authenticator-core/dist/authenticator/IJoseUtility'.
[2] @solid/authenticator-browser: ERROR in /Users/michiel/gh/inrupt/solid-auth-fetcher/packages/authenticator-browser/src/index.ts
[2] @solid/authenticator-browser: ./src/index.ts
[2] @solid/authenticator-browser: [tsl] ERROR in /Users/michiel/gh/inrupt/solid-auth-fetcher/packages/authenticator-browser/src/index.ts(4,31)
[2] @solid/authenticator-browser:       TS2307: Cannot find module '@solid/authenticator-core'.
[2] @solid/authenticator-browser: ERROR in /Users/michiel/gh/inrupt/solid-auth-fetcher/packages/authenticator-browser/src/index.ts
[2] @solid/authenticator-browser: ./src/index.ts
[2] @solid/authenticator-browser: [tsl] ERROR in /Users/michiel/gh/inrupt/solid-auth-fetcher/packages/authenticator-browser/src/index.ts(7,27)
[2] @solid/authenticator-browser:       TS2307: Cannot find module '@solid/authenticator-core/dist/authenticator/Authenticator'.
[2] @solid/authenticator-browser: ERROR in /Users/michiel/gh/inrupt/solid-auth-fetcher/packages/authenticator-browser/src/storage/InMemoryStorage.ts
[2] @solid/authenticator-browser: ./src/storage/InMemoryStorage.ts
[2] @solid/authenticator-browser: [tsl] ERROR in /Users/michiel/gh/inrupt/solid-auth-fetcher/packages/authenticator-browser/src/storage/InMemoryStorage.ts(4,22)
[2] @solid/authenticator-browser:       TS2307: Cannot find module '@solid/authenticator-core/dist/authenticator/IStorage'.
[2] @solid/authenticator-browser: Child html-webpack-plugin for "index.html":
[2] @solid/authenticator-browser:      1 asset
[2] @solid/authenticator-browser:     Entrypoint undefined = index.html
[2] @solid/authenticator-browser:     [../../node_modules/html-webpack-plugin/lib/loader.js!./src/index.html] /Users/michiel/gh/inrupt/solid-auth-fetcher/node_modules/html-webpack-plugin/lib/loader.js!./src/index.html 1.23 KiB {0} [built]
[2] @solid/authenticator-browser:     [../../node_modules/lodash/lodash.js] /Users/michiel/gh/inrupt/solid-auth-fetcher/node_modules/lodash/lodash.js 528 KiB {0} [built]
[2] @solid/authenticator-browser:     [../../node_modules/webpack/buildin/global.js] (webpack)/buildin/global.js 472 bytes {0} [built]
[2] @solid/authenticator-browser: ℹ ｢wdm｣: Failed to compile.
[2] @solid/authenticator-browser:     [../../node_modules/webpack/buildin/module.js] (webpack)/buildin/module.js 497 bytes {0} [built]
[1] @solid/authenticator-core: 11:00:56 AM - Found 0 errors. Watching for file changes.
[2] @solid/authenticator-browser: ℹ ｢wdm｣: Compiling...
[2] @solid/authenticator-browser: ✖ ｢wdm｣: Hash: 2bb97c6ab0f3b5aec025
[2] @solid/authenticator-browser: Version: webpack 4.42.0
[2] @solid/authenticator-browser: Time: 2045ms
[2] @solid/authenticator-browser: Built at: 03/16/2020 11:01:00 AM
[2] @solid/authenticator-browser:                         Asset      Size  Chunks             Chunk Names
[2] @solid/authenticator-browser:                    index.html  1.07 KiB          [emitted]  
[2] @solid/authenticator-browser: solid-authenticator.bundle.js  8.76 MiB    main  [emitted]  main
[2] @solid/authenticator-browser: Entrypoint main = solid-authenticator.bundle.js
[2] @solid/authenticator-browser: [../../node_modules/reflect-metadata/Reflect.js] /Users/michiel/gh/inrupt/solid-auth-fetcher/node_modules/reflect-metadata/Reflect.js 50 KiB {main} [built]
[2] @solid/authenticator-browser: [../../node_modules/tsyringe/dist/esm5/index.js] /Users/michiel/gh/inrupt/solid-auth-fetcher/node_modules/tsyringe/dist/esm5/index.js 388 bytes {main} [built]
[2] @solid/authenticator-browser: [../authenticator-core/dist/authenticatedFetch/AggregateAuthenticatedFetcher.js] 2.44 KiB {main} [built]
[2] @solid/authenticator-browser: [../authenticator-core/dist/authenticatedFetch/bearer/BearerAuthenticatedFetcher.js] 3.59 KiB {main} [built]
[2] @solid/authenticator-browser: [../authenticator-core/dist/authenticatedFetch/dpop/DpopAuthenticatedFetcher.js] 6.44 KiB {main} [built]
[2] @solid/authenticator-browser: [../authenticator-core/dist/authenticator/Authenticator.js] 7.23 KiB {main} [built]
[2] @solid/authenticator-browser: [../authenticator-core/dist/index.js] 4.57 KiB {main} [built]
[2] @solid/authenticator-browser: [../authenticator-core/dist/login/AggregateLoginHandler.js] 2.36 KiB {main} [built]
[2] @solid/authenticator-browser: [../authenticator-core/dist/login/oidc/AggregateOidcHandler.js] 2.36 KiB {main} [built]
[2] @solid/authenticator-browser: [../authenticator-core/dist/login/oidc/IssuerConfigFetcher.js] 9.79 KiB {main} [built]
[2] @solid/authenticator-browser: [../authenticator-core/dist/login/oidc/OidcLoginHandler.js] 6.34 KiB {main} [built]
[2] @solid/authenticator-browser: [../authenticator-core/dist/login/oidc/oidcHandlers/AuthorizationCodeOidcHandler.js] 3.55 KiB {main} [built]
[2] @solid/authenticator-browser: [../authenticator-core/dist/login/oidc/oidcHandlers/AuthorizationCodeWithPkceOidcHandler.js] 3.61 KiB {main} [built]
[2] @solid/authenticator-browser: [../authenticator-core/dist/login/oidc/oidcHandlers/ClientCredentialsOidcHandler.js] 3.55 KiB {main} [built]
[2] @solid/authenticator-browser: [../authenticator-core/dist/login/oidc/oidcHandlers/LegacyImplicitFlowOidcHandler.js] 5.94 KiB {main} [built]
[2] @solid/authenticator-browser:     + 436 hidden modules
[2] @solid/authenticator-browser: ERROR in /Users/michiel/gh/inrupt/solid-auth-fetcher/packages/authenticator-browser/src/BrowserJoseUtility.ts
[2] @solid/authenticator-browser: ./src/BrowserJoseUtility.ts
[2] @solid/authenticator-browser: [tsl] ERROR in /Users/michiel/gh/inrupt/solid-auth-fetcher/packages/authenticator-browser/src/BrowserJoseUtility.ts(18,26)
[2] @solid/authenticator-browser:       TS2307: Cannot find module '@solid/authenticator-core/dist/authenticator/IJoseUtility'.
[2] @solid/authenticator-browser: ERROR in /Users/michiel/gh/inrupt/solid-auth-fetcher/packages/authenticator-browser/src/index.ts
[2] @solid/authenticator-browser: ./src/index.ts
[2] @solid/authenticator-browser: [tsl] ERROR in /Users/michiel/gh/inrupt/solid-auth-fetcher/packages/authenticator-browser/src/index.ts(4,31)
[2] @solid/authenticator-browser:       TS2307: Cannot find module '@solid/authenticator-core'.
[2] @solid/authenticator-browser: ERROR in /Users/michiel/gh/inrupt/solid-auth-fetcher/packages/authenticator-browser/src/index.ts
[2] @solid/authenticator-browser: ./src/index.ts
[2] @solid/authenticator-browser: [tsl] ERROR in /Users/michiel/gh/inrupt/solid-auth-fetcher/packages/authenticator-browser/src/index.ts(7,27)
[2] @solid/authenticator-browser:       TS2307: Cannot find module '@solid/authenticator-core/dist/authenticator/Authenticator'.
[2] @solid/authenticator-browser: ERROR in /Users/michiel/gh/inrupt/solid-auth-fetcher/packages/authenticator-browser/src/storage/InMemoryStorage.ts
[2] @solid/authenticator-browser: ./src/storage/InMemoryStorage.ts
[2] @solid/authenticator-browser: [tsl] ERROR in /Users/michiel/gh/inrupt/solid-auth-fetcher/packages/authenticator-browser/src/storage/InMemoryStorage.ts(4,22)
[2] @solid/authenticator-browser:       TS2307: Cannot find module '@solid/authenticator-core/dist/authenticator/IStorage'.
[2] @solid/authenticator-browser: Child html-webpack-plugin for "index.html":
[2] @solid/authenticator-browser:      1 asset
[2] @solid/authenticator-browser:     Entrypoint undefined = index.html
[2] @solid/authenticator-browser:        4 modules
[2] @solid/authenticator-browser: ℹ ｢wdm｣: Failed to compile.

**Comment by jaxoncreed** [comment]
Fixed
